# Generated by Django 4.1.3 on 2022-12-05 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fr_attendance", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faculty",
            name="phone",
        ),
        migrations.AddField(
            model_name="attendence",
            name="classname",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="classname",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="branch",
            field=models.CharField(
                choices=[("CIS", "CIS"), ("EEC", "EEC")], max_length=100, null=True
            ),
        ),
    ]
