# Generated by Django 4.1.3 on 2022-12-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fr_attendance", "0002_remove_faculty_phone_attendence_classname_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendence",
            old_name="branch",
            new_name="courses",
        ),
        migrations.RemoveField(
            model_name="attendence",
            name="classname",
        ),
        migrations.RemoveField(
            model_name="student",
            name="branch",
        ),
        migrations.RemoveField(
            model_name="student",
            name="classname",
        ),
        migrations.AddField(
            model_name="student",
            name="courses",
            field=models.CharField(
                choices=[
                    ("CIS620", "CIS620"),
                    ("CIS524/424", "CIS524/424"),
                    ("CIS600 ", "CIS600"),
                    ("CIS550/390", "CIS550/390"),
                    ("CIS530/430", "CIS530/430"),
                    ("CIS636/EEC623", "CIS636/EEC623"),
                    ("CIS634", "CIS634"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
