# Generated by Django 4.1.3 on 2022-12-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fr_attendance", "0005_alter_student_courses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="courses",
            field=models.CharField(
                choices=[
                    ("CIS620", "CIS620"),
                    ("CIS524/424", "CIS524/424-Programming Languages"),
                    ("CIS600 ", "CIS600"),
                    ("CIS550/390", "CIS550/390"),
                    ("CIS530/430", "CIS530/430"),
                    ("CIS636/EEC623", "CIS636/EEC623"),
                    ("CIS634", "CIS634"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
