# Generated by Django 4.1.3 on 2022-12-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fr_attendance", "0006_alter_student_courses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="courses",
            field=models.CharField(
                choices=[
                    ("CIS620", "CIS620-Advanced Operating Systems"),
                    ("CIS524/424", "CIS524/424-Programming Languages"),
                    ("CIS600 ", "CIS600-Advanced Computer Architecture"),
                    ("CIS550/390", "CIS550/390-Introduction to Algorithms"),
                    ("CIS530/430", "CIS530/430-Database System and Processing"),
                    ("CIS636/EEC623", "CIS636/EEC623-Software Quality Assurance"),
                    ("CIS634", "CIS634-Object-Oriented Software Engineering"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
