# Generated by Django 4.1.3 on 2022-12-05 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fr_attendance", "0008_attendence_firstname_attendence_lastname"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendence",
            name="firstname",
        ),
        migrations.RemoveField(
            model_name="attendence",
            name="lastname",
        ),
    ]
