# Generated by Django 4.1.3 on 2022-12-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fr_attendance", "0009_remove_attendence_firstname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendence",
            name="firstname",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="attendence",
            name="lastname",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
